import { Agent, run, setDefaultOpenAIKey } from '@openai/agents';
import { z } from 'zod';

export type ExpenseAgentClassification = 'expense' | 'off_topic';

export interface ExpenseAgentInput {
  text: string | null;
  username?: string;
}

export interface AmendLastExpense {
  name: string | null;
  amount: number | null;
}

export interface ExpenseAgentAnalysis {
  classification: ExpenseAgentClassification;
  amount: number | null;
  reply: string;
  detail: string | null;
  deleteLastExpense: boolean;
  amendLastExpense: AmendLastExpense | null;
  sumMonthlyExpenses: boolean;
  listMonthlyExpenses: boolean;
}

export interface ExpenseAgentRuntime {
  analyze(input: ExpenseAgentInput): Promise<ExpenseAgentAnalysis>;
}


const expenseAgentOutputSchema = z.object({
  classification: z.union([z.literal('expense'), z.literal('off_topic')]),
  amount: z.number().or(z.null()).describe('The amount of the expense or null if the message is off-topic'),
  reply: z.string().describe('The reply to the message in Argentine Spanish'),
  detail: z.string().or(z.null()).describe('The detail of the expense or null if the message is off-topic'),
  deleteLastExpense: z
    .boolean()
    .describe('True when the user asks to delete, undo, or remove the last logged expense'),
  amendLastExpense: z
    .object({
      name: z.string().nullable().describe('New name/detail for the last expense, or null if not changing'),
      amount: z.number().nullable().describe('New amount for the last expense, or null if not changing'),
    })
    .nullable()
    .describe('Set to an object with the fields to update when the user wants to amend the last expense name or amount. Null otherwise.'),
  sumMonthlyExpenses: z
    .boolean()
    .describe('True when the user asks for the total amount spent so far in the current month'),
  listMonthlyExpenses: z
    .boolean()
    .describe('True when the user asks to see the list of all expenses for the current month'),
});

let runtimeInstance: ExpenseAgentRuntime | undefined;

function buildAgentInstructions(): string {
  return [
    'You are an expense accountability partner in a private Telegram chat.',
    'You track expenses for an Argentine couple in his mid 30s, amounts are in ARS.',
    'Classify each incoming message as either an expense report or off-topic:',
    '- Respond with classification "expense" when the message clearly describes money being spent, ' +
      'purchases, bills, or financial outflows.',
    '- Respond with classification "off_topic" for anything else, including empty or undecipherable content.',
    'When the classification is "expense", check that amount and details are provided, otherwise, ask for them. If everything is provided, confirm that the expense was logged in the database.',
    'When the classification is "off_topic", reply with a short statement that the message is off-topic.',
    'Set "deleteLastExpense" to true when the user asks to delete, undo, or remove the last logged expense ' +
      '(e.g. "borra el ultimo gasto", "eliminá lo último", "deshacé el último gasto"). Otherwise set it to false.',
    'Set "amendLastExpense" to an object when the user wants to correct or update the last logged expense ' +
      '(e.g. "cambia el importe del gasto anterior por 500", "modifica el nombre del gasto por supermercado", ' +
      '"el monto era 1200", "corregí el último gasto, era 300"). ' +
      'Include "name" if the user specifies a new name/detail, include "amount" if a new amount is given. ' +
      'Set "amendLastExpense" to null otherwise.',
    'Set "sumMonthlyExpenses" to true when the user asks how much has been spent so far this month ' +
      '(e.g. "cuánto llevamos gastado este mes", "sumá los gastos del mes", "total?", "cuánto va?", "el total?", "total del mes?"). Otherwise set it to false.',
    'Set "listMonthlyExpenses" to true when the user asks to see the list or detail of all expenses for the current month ' +
      '(e.g. "mostrame los gastos del mes", "qué gastamos este mes", "listá los gastos"). Otherwise set it to false.',
    'When "deleteLastExpense", "sumMonthlyExpenses", or "listMonthlyExpenses" is true, you may leave "reply" as a short placeholder, ' +
      'since the confirmation message is generated by the system after the action runs.',
    'Use only information provided in the message text. If there is no usable text, treat it as off_topic.',
    'The final output must conform to the provided JSON schema.',
  ].join('\n');
}

function ensureRuntime(): ExpenseAgentRuntime {
  if (runtimeInstance) {
    return runtimeInstance;
  }

  const apiKey = process.env.OPENAI_API_KEY;
  if (!apiKey) {
    throw new Error('OPENAI_API_KEY is not set');
  }

  setDefaultOpenAIKey(apiKey);

  const agent = new Agent({
    name: 'Expensator',
    instructions: buildAgentInstructions(),
    outputType: expenseAgentOutputSchema,
    model: 'gpt-4.1-mini'
  });

  runtimeInstance = {
    async analyze(input: ExpenseAgentInput): Promise<ExpenseAgentAnalysis> {
      const messageText = input.text?.trim();

      const promptLines: string[] = [];

      if (input.username) {
        promptLines.push(`Sender username: ${input.username}`);
      }

      promptLines.push('Message:');
      promptLines.push(
        messageText && messageText.length > 0
          ? messageText
          : '[no text provided]'
      );

      const result = await run(agent, promptLines.join('\n'));
      const output = result.finalOutput;

      if (!output) {
        throw new Error('Agent returned no output');
      }

      return output;
    }
  };

  return runtimeInstance;
}

export function getExpenseAgentRuntime(): ExpenseAgentRuntime {
  return ensureRuntime();
}

export async function analyzeExpenseMessage(
  input: ExpenseAgentInput
): Promise<ExpenseAgentAnalysis> {
  const runtime = getExpenseAgentRuntime();
  return runtime.analyze(input);
}
